# Generated by Django 4.0.5 on 2022-07-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_historicaluser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado'), ('eliminado', 'Eliminado')], default='active', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado'), ('eliminado', 'Eliminado')], default='active', max_length=10, verbose_name='status'),
        ),
    ]
