# Generated by Django 4.0.4 on 2022-06-22 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=6, unique=True, verbose_name='Matricula')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Celular')),
                ('ocupation', models.CharField(max_length=255, null=True, verbose_name='Ocupacion')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('relocate', models.BooleanField(default=False, verbose_name='Recolocacion')),
                ('cv', models.FileField(null=True, upload_to='alumn/cv', verbose_name='Curriculo')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'ALUMN',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('postulado', 'Postulado'), ('visto', 'Visto'), ('programado para entrevistar', 'Programado para entrevistar'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='postulado', max_length=30, verbose_name='Estado')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensaje')),
                ('interview_date', models.DateTimeField(verbose_name='Fecha para entrevista')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificaón')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('country', models.CharField(max_length=55, null=True, verbose_name='País')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
                'db_table': 'COMPANY',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55, verbose_name='Titulo')),
                ('workplace', models.CharField(choices=[('remoto', 'Remoto'), ('presencial', 'Presencial'), ('hibrido', 'Hbrido')], max_length=10, verbose_name='Lugar de trabajo')),
                ('ubication', models.CharField(max_length=55, verbose_name='Ubicación')),
                ('job_type', models.CharField(choices=[('tiempo completo', 'Tiempo completo'), ('medio tiempo', 'Medio tiempo'), ('indeterminado', 'Iderterminado'), ('temporal', 'Temporal'), ('voluntariado', 'Voluntariado'), ('prácticas', 'Prácticas')], max_length=15, verbose_name='Tipo de trabajo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('salary', models.FloatField(verbose_name='Salario')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('eliminated', 'eliminated')], default='active', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificaón')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
            ],
            options={
                'verbose_name': 'Empleo',
                'verbose_name_plural': 'Empleos',
                'db_table': 'JOB',
            },
        ),
    ]
