# Generated by Django 4.0.5 on 2022-07-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_company_address_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='interview_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha para entrevista'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('postulado', 'Postulado'), ('visto', 'Visto'), ('programado para entrevistar', 'Programado para entrevistar'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('eliminado', 'Eliminado')], default='postulado', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado'), ('eliminado', 'Eliminado')], default='active', max_length=10, verbose_name='Estado'),
        ),
    ]
